<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class ComboOfferController extends Controller
{
    /**
     * Get all predefined Diwali Value Combos
     */
    public static function getCombos()
    {
        return [
            'combo_3k' => [
                'id' => 'combo_3k',
                'sku' => 'RC-COMBO-3K',
                'numeric_id' => 999300,
                'name' => '3K COMBO — Diwali Value Pack',
                'badge' => 'FAMILY BUDGET COMBO',
                'tagline' => '44 Products • 77 Total Items',
                'total_products' => 44,
                'total_qty' => 77,
                'original_price' => 4500,
                'offer_price' => 3000,
                'savings' => 1500,
                'color' => '#E05A1B',
                'highlight' => false,
                'description' => 'Perfect family cracker celebration pack featuring sparklers, chakkars, flower pots, rockets, and sound crackers at an unbeatable wholesale offer.',
                'items' => [
                    ['no' => 1, 'name' => '4" Dlx Gold Lakshmi', 'pack' => '1 Pkt/5 Pcs', 'qty' => 5],
                    ['no' => 2, 'name' => '2 3/4" Kuruvi', 'pack' => '1 Pkt/5 Pcs', 'qty' => 10],
                    ['no' => 3, 'name' => '5" Jallikattu', 'pack' => '1 Pkt/5 Pcs', 'qty' => 1],
                    ['no' => 4, 'name' => '6" Kumki', 'pack' => '1 Pkt/50 Pcs', 'qty' => 1],
                    ['no' => 5, 'name' => 'Red Bijili', 'pack' => '1 Pkt/100 Pcs', 'qty' => 1],
                    ['no' => 6, 'name' => 'Red Bijili', 'pack' => '1 Box/100 Pcs', 'qty' => 1],
                    ['no' => 7, 'name' => 'Hydro Bomb', 'pack' => '1 Box/10 Pcs', 'qty' => 1],
                    ['no' => 8, 'name' => 'Jurassic Bomb (3Ply)', 'pack' => '1 Box/10 Pcs', 'qty' => 1],
                    ['no' => 9, 'name' => 'Rocket Bomb', 'pack' => '1 Box/10 Pcs', 'qty' => 1],
                    ['no' => 10, 'name' => '1k Radhe Half', 'pack' => '1 Box/1 Pce', 'qty' => 1],
                    ['no' => 11, 'name' => '7 cm Electric Sparklers', 'pack' => '1 Box/10 Pcs', 'qty' => 10],
                    ['no' => 12, 'name' => '10 cm Colour Sparkles', 'pack' => '1 Box/10 Pcs', 'qty' => 10],
                    ['no' => 13, 'name' => '15 cm Electric Sparklers', 'pack' => '1 Box/10 Pcs', 'qty' => 2],
                    ['no' => 14, 'name' => '1/2" Twinkling Star', 'pack' => '1 Box/10 Pcs', 'qty' => 1],
                    ['no' => 15, 'name' => '4" Twinkling Star', 'pack' => '1 Box/10 Pcs', 'qty' => 1],
                    ['no' => 16, 'name' => 'Flash Handle', 'pack' => '1 Box/5 Pcs', 'qty' => 1],
                    ['no' => 17, 'name' => 'Flower Pots Big Regular', 'pack' => '1 Box/10 Pcs', 'qty' => 1],
                    ['no' => 18, 'name' => 'Flower Pots Ashoka Regular', 'pack' => '1 Box/10 Pcs', 'qty' => 1],
                    ['no' => 19, 'name' => 'Ground Chakkar Big (10 Pcs) Spinner', 'pack' => '1 Box/10 Pcs', 'qty' => 1],
                    ['no' => 20, 'name' => 'Ground Chakkar Big (25 Pcs) Spinner', 'pack' => '1 Box/25 Pcs', 'qty' => 1],
                    ['no' => 21, 'name' => 'Disco Wheel', 'pack' => '1 Box/10 Pcs', 'qty' => 1],
                    ['no' => 22, 'name' => 'Golden Rain', 'pack' => '1 Box/5 Pcs', 'qty' => 1],
                    ['no' => 23, 'name' => 'Peacock Feather', 'pack' => '1 Box/5Pcs', 'qty' => 1],
                    ['no' => 24, 'name' => '5 in 1 Shower', 'pack' => '1 Box/5Pcs', 'qty' => 1],
                    ['no' => 25, 'name' => '21/4 Retro Series (5 Varieties)', 'pack' => '1 Box/1Pcs', 'qty' => 2],
                    ['no' => 26, 'name' => '4" Smile Day (5 Varieties)', 'pack' => '1 Box/1Pcs', 'qty' => 1],
                    ['no' => 27, 'name' => '6" Red and Green Shower', 'pack' => '1 Tin', 'qty' => 1],
                    ['no' => 28, 'name' => 'Photo Flash', 'pack' => '1 Box/5 Pcs', 'qty' => 1],
                    ['no' => 29, 'name' => 'Helicopter', 'pack' => '1 Box/5 Pcs', 'qty' => 1],
                    ['no' => 30, 'name' => '1 3/4" Chotta Fancy (5 Varieties)', 'pack' => '1 Box/1Pcs', 'qty' => 1],
                    ['no' => 31, 'name' => '12 Radhe Raider', 'pack' => '1 Box/1Pcs', 'qty' => 1],
                    ['no' => 32, 'name' => '15 Shot Premium', 'pack' => '1 Box/1Pcs', 'qty' => 1],
                    ['no' => 33, 'name' => '10 in 1 King Match box', 'pack' => '1 Box/10 Pcs', 'qty' => 1],
                    ['no' => 34, 'name' => '10 in 1 Chakra Match box', 'pack' => '1 Box/10 Pcs', 'qty' => 1],
                    ['no' => 35, 'name' => 'Black Serpent', 'pack' => '1 Bundle/10 Box', 'qty' => 1],
                    ['no' => 36, 'name' => 'Anaconda Coin', 'pack' => '1 Box/10 Coins', 'qty' => 1],
                    ['no' => 37, 'name' => 'Roll cap and Gun (1 gun)', 'pack' => '1 Box / 100 Pcs', 'qty' => 1],
                    ['no' => 38, 'name' => 'Radhe Dual Gun 0022 &Ringcap (Multi Colour)', 'pack' => '1 Box/2 Caps', 'qty' => 1],
                    ['no' => 39, 'name' => 'Parachute', 'pack' => '1 Pkt/1 Pce', 'qty' => 1],
                    ['no' => 40, 'name' => 'Kitkat', 'pack' => '1 Box/10 Pcs', 'qty' => 1],
                    ['no' => 41, 'name' => 'Purple Dove (Ayyan)', 'pack' => '1 Box/1Pcs', 'qty' => 1],
                    ['no' => 42, 'name' => 'Mowgli 28 Chorsa', 'pack' => '1 Box/5 Pcs', 'qty' => 1],
                    ['no' => 43, 'name' => '100 W-power', 'pack' => '1 Box/5 Pcs', 'qty' => 1],
                    ['no' => 44, 'name' => '250G', 'pack' => '1 Box/1 Pce', 'qty' => 1],
                ],
            ],
            'combo_5k' => [
                'id' => 'combo_5k',
                'sku' => 'RC-COMBO-5K',
                'numeric_id' => 999500,
                'name' => '5K COMBO — Diwali Value Pack',
                'badge' => 'MOST POPULAR CHOICE',
                'tagline' => '50 Products • 102 Total Items',
                'total_products' => 50,
                'total_qty' => 102,
                'original_price' => 7500,
                'offer_price' => 5000,
                'savings' => 2500,
                'color' => '#B67121',
                'highlight' => true,
                'description' => 'Our best-selling Diwali combo with high-impact aerial shots, multi-color sparklers, deluxe spinners, flower pots, sound bombs, and novelty items for the whole family.',
                'items' => [
                    ['no' => 1, 'name' => '4" Dlx Gold Lakshmi', 'pack' => '1 Pkt/5 Pcs', 'qty' => 10],
                    ['no' => 2, 'name' => '2 3/4" Kuruvi', 'pack' => '1 Pkt/5 Pcs', 'qty' => 10],
                    ['no' => 3, 'name' => '3.5" Lakshmi', 'pack' => '1 Pkt/5 Pcs', 'qty' => 10],
                    ['no' => 4, 'name' => '5" Jallikattu', 'pack' => '1 Pkt/5 Pcs', 'qty' => 5],
                    ['no' => 5, 'name' => '6" Kumki', 'pack' => '1 Pkt/5 Pcs', 'qty' => 5],
                    ['no' => 6, 'name' => 'Red Bijili', 'pack' => '1 Pkt/100 Pcs', 'qty' => 1],
                    ['no' => 7, 'name' => 'Stripped Bijili', 'pack' => '1 Pkt/100 Pcs', 'qty' => 1],
                    ['no' => 8, 'name' => 'Hydro Bomb', 'pack' => '1 Box/10 Pcs', 'qty' => 1],
                    ['no' => 9, 'name' => 'Jurassic Bomb (3Ply)', 'pack' => '1 Box/10 Pcs', 'qty' => 1],
                    ['no' => 10, 'name' => 'Whistling Rocket', 'pack' => '1 Box/10 Pcs', 'qty' => 1],
                    ['no' => 11, 'name' => '1k Radhe Half', 'pack' => '1 Box/1 Pce', 'qty' => 1],
                    ['no' => 12, 'name' => '10 cm Electric Sparklers', 'pack' => '1 Box/10 Pcs', 'qty' => 10],
                    ['no' => 13, 'name' => '12 cm Colour Sparkles', 'pack' => '1 Box/10 Pcs', 'qty' => 5],
                    ['no' => 14, 'name' => '15 cm Electric Sparklers', 'pack' => '1 Box/10 Pcs', 'qty' => 2],
                    ['no' => 15, 'name' => '15 cm Colour Sparkles', 'pack' => '1 Box/10 Pcs', 'qty' => 2],
                    ['no' => 16, 'name' => '30 cm Electric Sparklers', 'pack' => '1 Box/5 Pcs', 'qty' => 2],
                    ['no' => 17, 'name' => '30 cm Colour Sparkles', 'pack' => '1 Box/5 Pcs', 'qty' => 2],
                    ['no' => 18, 'name' => '15 Cm Silver Sparkles', 'pack' => '1 Box/5 Pcs', 'qty' => 1],
                    ['no' => 19, 'name' => '4" Twinkling Star', 'pack' => '1 Box/10 Pcs', 'qty' => 1],
                    ['no' => 20, 'name' => 'Flash Handle', 'pack' => '1 Box/ 5 Pcs', 'qty' => 1],
                    ['no' => 21, 'name' => 'Flower Pots Ashoka Regular', 'pack' => '1 Box/10 Pcs', 'qty' => 1],
                    ['no' => 22, 'name' => 'Flower Pots Colour Koti Regular', 'pack' => '1 Box/10 Pcs', 'qty' => 1],
                    ['no' => 23, 'name' => 'Ground Chakkar Big (25 Pcs) Spinner', 'pack' => '1 Box/25 Pcs', 'qty' => 1],
                    ['no' => 24, 'name' => 'Ground Chakkar Deluxe Spinner', 'pack' => '1 Box/10 Pcs', 'qty' => 1],
                    ['no' => 25, 'name' => 'Cocktail Spinners (10 colours in 1 box) (Ayyan)', 'pack' => '1 Box/10Pcs', 'qty' => 1],
                    ['no' => 26, 'name' => 'Disco Wheel', 'pack' => '1 Box/10 Pcs', 'qty' => 1],
                    ['no' => 27, 'name' => 'Dancinig Peacock 3 Step (multi colour)', 'pack' => '1 Pce', 'qty' => 1],
                    ['no' => 28, 'name' => 'Golden Rain', 'pack' => '1 Box/5 Pcs', 'qty' => 1],
                    ['no' => 29, 'name' => '5 in 1 Shower', 'pack' => '1 Box/5Pcs', 'qty' => 1],
                    ['no' => 30, 'name' => '4" Smile Day (5 Varieties)', 'pack' => '1 Box/1Pcs', 'qty' => 1],
                    ['no' => 31, 'name' => '6" Red and Green Shower', 'pack' => '1 Tin', 'qty' => 1],
                    ['no' => 32, 'name' => 'Photo Flash', 'pack' => '1 Box/5 Pcs', 'qty' => 1],
                    ['no' => 33, 'name' => 'Bambara', 'pack' => '1 Box/10 Pcs', 'qty' => 1],
                    ['no' => 34, 'name' => 'Helicopter', 'pack' => '1 Box/5 Pcs', 'qty' => 1],
                    ['no' => 35, 'name' => '1 3/4" Chotta Fancy (5 Varieties)', 'pack' => '1 Box/1Pce', 'qty' => 1],
                    ['no' => 36, 'name' => '2" Fancy (Silver)', 'pack' => '1 Box/1Pce', 'qty' => 1],
                    ['no' => 37, 'name' => '3.5" Fancy (Red)', 'pack' => '1 Box/1Pce', 'qty' => 1],
                    ['no' => 38, 'name' => '25 Radhe Raider', 'pack' => '1 Box/1Pce', 'qty' => 1],
                    ['no' => 39, 'name' => '30 Shot Regular', 'pack' => '1 Box/1Pce', 'qty' => 1],
                    ['no' => 40, 'name' => '10 in 1 Chakra Match box', 'pack' => '1 Box/10 Pcs', 'qty' => 1],
                    ['no' => 41, 'name' => 'Black Serpent', 'pack' => '1 Bundle/10 Box', 'qty' => 1],
                    ['no' => 42, 'name' => 'Roll cap and Gun (1 gun)', 'pack' => '1 Box / 100 Pcs', 'qty' => 1],
                    ['no' => 43, 'name' => 'Radhe Dual Gun 0022 & Ringcap (Multi Colour)', 'pack' => '1 Pce & 2 Caps', 'qty' => 1],
                    ['no' => 44, 'name' => 'Parachute', 'pack' => '1 Pkt/1 Pce', 'qty' => 1],
                    ['no' => 45, 'name' => 'Kitkat', 'pack' => '1 Box/10 Pcs', 'qty' => 1],
                    ['no' => 46, 'name' => 'Money in the Bank', 'pack' => '1 Pkt/3 Pcs', 'qty' => 1],
                    ['no' => 47, 'name' => 'Lemon Tree Fountain (4 Colour Varities) (Ayyan)', 'pack' => '1Pce', 'qty' => 1],
                    ['no' => 48, 'name' => 'Barlie Purple / Jea Boom Ba Blue', 'pack' => '1Pce', 'qty' => 1],
                    ['no' => 49, 'name' => 'Mowgli 28 Chorsa', 'pack' => '1 Box/5 Pcs', 'qty' => 1],
                    ['no' => 50, 'name' => '500G', 'pack' => '1 Box/ 1 Pce', 'qty' => 1],
                ],
            ],
            'combo_8k' => [
                'id' => 'combo_8k',
                'sku' => 'RC-COMBO-8K',
                'numeric_id' => 999800,
                'name' => '8K COMBO — Diwali Value Pack',
                'badge' => 'GRAND CELEBRATION COMBO',
                'tagline' => '66 Products • 121 Total Items',
                'total_products' => 66,
                'total_qty' => 121,
                'original_price' => 11500,
                'offer_price' => 8000,
                'savings' => 3500,
                'color' => '#1E093B',
                'highlight' => false,
                'description' => 'The ultimate grand festival feast! Features a staggering 66 branded fireworks items including multi-shot repeaters, 50 Radhe Raider, 60 Shot Regular, 1KG crackers, fancy aerials, and jumbo sparklers.',
                'items' => [
                    ['no' => 1, 'name' => '4" Dlx Gold Lakshmi', 'pack' => '1 Pkt/5 Pcs', 'qty' => 10],
                    ['no' => 2, 'name' => '2 3/4" Kuruvi', 'pack' => '1 Pkt/5 Pcs', 'qty' => 25],
                    ['no' => 3, 'name' => '4" Lakshmi/Hulk', 'pack' => '1 Pkt/5 Pcs', 'qty' => 10],
                    ['no' => 4, 'name' => '5" Jallikattu', 'pack' => '1 Pkt/5 Pcs', 'qty' => 5],
                    ['no' => 5, 'name' => 'Red Bijili', 'pack' => '1 Pkt/100 Pcs', 'qty' => 1],
                    ['no' => 6, 'name' => 'Stripped Bijili', 'pack' => '1 Pkt/100 Pcs', 'qty' => 1],
                    ['no' => 7, 'name' => 'Jurassic Bomb (3Ply)', 'pack' => '1 Box/10 Pcs', 'qty' => 1],
                    ['no' => 8, 'name' => 'King of King (7 Ply)', 'pack' => '1 Box/10 Pcs', 'qty' => 1],
                    ['no' => 9, 'name' => 'Lunik Express Rocket', 'pack' => '1 Box/10 Pcs', 'qty' => 1],
                    ['no' => 10, 'name' => 'Whistling Rocket', 'pack' => '1 Box/10 Pcs', 'qty' => 1],
                    ['no' => 11, 'name' => '1k Radhe Half', 'pack' => '1 Box/1 Pce', 'qty' => 1],
                    ['no' => 12, 'name' => '2k Radhe Half', 'pack' => '1 Box/1 Pce', 'qty' => 1],
                    ['no' => 13, 'name' => '12 cm Colour Sparkles', 'pack' => '1 Box/10 Pcs', 'qty' => 4],
                    ['no' => 14, 'name' => '15 cm Colour Sparkles', 'pack' => '1 Box/10 Pcs', 'qty' => 4],
                    ['no' => 15, 'name' => '30 cm Colour Sparkles', 'pack' => '1 Box/5 Pcs', 'qty' => 4],
                    ['no' => 16, 'name' => '50 cm Electric Sparklers(5pcs)', 'pack' => '1 Box/5 Pcs', 'qty' => 1],
                    ['no' => 17, 'name' => '50 cm Colour Sparkles (5pcs)', 'pack' => '1 Box/5 Pcs', 'qty' => 1],
                    ['no' => 18, 'name' => 'Rainbow Sparkles (Smoking Stick)', 'pack' => '1 Box/10 Pcs', 'qty' => 1],
                    ['no' => 19, 'name' => '15 Cm Pink Sparkles', 'pack' => '1 Box/5 Pcs', 'qty' => 1],
                    ['no' => 20, 'name' => '1/2" Twinkling Star', 'pack' => '1 Box/10 Pcs', 'qty' => 1],
                    ['no' => 21, 'name' => '4" Twinkling Star', 'pack' => '1 Box/10 Pcs', 'qty' => 1],
                    ['no' => 22, 'name' => 'Flash Handle', 'pack' => '1 Box/ 5 Pcs', 'qty' => 1],
                    ['no' => 23, 'name' => 'Flower Pots Big Regular', 'pack' => '1 Box/10 Pcs', 'qty' => 1],
                    ['no' => 24, 'name' => 'Flower Pots Ashoka Regular', 'pack' => '1 Box/10 Pcs', 'qty' => 1],
                    ['no' => 25, 'name' => 'Flower Pots Colour Koti Regular', 'pack' => '1 Box/10 Pcs', 'qty' => 1],
                    ['no' => 26, 'name' => 'Ground Chakkar Big (10 Pcs) Spinner', 'pack' => '1 Box/10 Pcs', 'qty' => 1],
                    ['no' => 27, 'name' => 'Ground Chakkar Asoka Spinner', 'pack' => '1 Box/10 Pcs', 'qty' => 1],
                    ['no' => 28, 'name' => 'Cocktail Spinners (10 colours in 1 box)', 'pack' => '1 Box/10Pcs', 'qty' => 1],
                    ['no' => 29, 'name' => 'Disco Wheel', 'pack' => '1 Box/10 Pcs', 'qty' => 1],
                    ['no' => 30, 'name' => 'Dancinig Peacock 3 Step (multi colour)', 'pack' => '1 Box/5 Pcs', 'qty' => 1],
                    ['no' => 31, 'name' => 'Golden Rain', 'pack' => '1 Box/5 Pcs', 'qty' => 1],
                    ['no' => 32, 'name' => 'Peacock Feather', 'pack' => '1 Box/5Pcs', 'qty' => 1],
                    ['no' => 33, 'name' => '5 in 1 Shower', 'pack' => '1 Box/5Pcs', 'qty' => 1],
                    ['no' => 34, 'name' => '13/4 Flower Series (5 Varieties)', 'pack' => '1 Box/5Pcs', 'qty' => 1],
                    ['no' => 35, 'name' => '21/4 Retro Series (5 Varieties)', 'pack' => '1 Box/1Pcs', 'qty' => 1],
                    ['no' => 36, 'name' => '4" Smile Day (5 Varieties)', 'pack' => '1 Box/1Pcs', 'qty' => 1],
                    ['no' => 37, 'name' => '6" Red and Green Shower', 'pack' => '1 Tin', 'qty' => 1],
                    ['no' => 38, 'name' => 'Photo Flash', 'pack' => '1 Box/5 Pcs', 'qty' => 1],
                    ['no' => 39, 'name' => 'Helicopter', 'pack' => '1 Box/5 Pcs', 'qty' => 1],
                    ['no' => 40, 'name' => 'Butterfly', 'pack' => '1 Box/10 Pcs', 'qty' => 1],
                    ['no' => 41, 'name' => 'Hand Smoke', 'pack' => '1 Box/ 3 Pcs', 'qty' => 1],
                    ['no' => 42, 'name' => '1 3/4" Chotta Fancy (5 Varieties)', 'pack' => '1 Box/1Pce', 'qty' => 1],
                    ['no' => 43, 'name' => '1" Pogo Mixed (5 Colour)', 'pack' => '1 Box/2Pce', 'qty' => 1],
                    ['no' => 44, 'name' => '2" Fancy (Silver)', 'pack' => '1 Box/1Pce', 'qty' => 1],
                    ['no' => 45, 'name' => '2 Fancy 3 Pcs Magic word', 'pack' => '1 Box/3Pcs', 'qty' => 1],
                    ['no' => 46, 'name' => '3.5" Fancy (White)', 'pack' => '1 Box/1Pce', 'qty' => 1],
                    ['no' => 47, 'name' => '3.5" Fancy (NAYAGARA FALLS)', 'pack' => '1 Box/1Pce', 'qty' => 1],
                    ['no' => 48, 'name' => '4" Premium Aerial', 'pack' => '1 Box/2 Pcs', 'qty' => 1],
                    ['no' => 49, 'name' => '50 Radhe Raider', 'pack' => '1 Box/1Pce', 'qty' => 1],
                    ['no' => 50, 'name' => '60 Shot Regular', 'pack' => '1 Box/1Pce', 'qty' => 1],
                    ['no' => 51, 'name' => '10 in 1 Chakra Match box', 'pack' => '1 Box/10 Pcs', 'qty' => 1],
                    ['no' => 52, 'name' => '10 in 1 Queen Match box', 'pack' => '1 Box/10 Pcs', 'qty' => 1],
                    ['no' => 53, 'name' => 'Anaconda Coin', 'pack' => '1 Box/10 Coins', 'qty' => 1],
                    ['no' => 54, 'name' => 'Roll cap and Gun (1 gun)', 'pack' => '1 Box / 100 Pcs', 'qty' => 1],
                    ['no' => 55, 'name' => 'Radhe Dual Gun 0022 &Ringcap (Multi Colour)', 'pack' => '1 Pce & 2 Caps', 'qty' => 1],
                    ['no' => 56, 'name' => 'Parachute', 'pack' => '1 Pkt/1 Pce', 'qty' => 1],
                    ['no' => 57, 'name' => 'Crackling Popcorn (ayyan)', 'pack' => '1 Box/10 Pcs', 'qty' => 1],
                    ['no' => 58, 'name' => 'olai vedi', 'pack' => '1 Pkt/25 Pcs', 'qty' => 1],
                    ['no' => 59, 'name' => 'Money in the Bank', 'pack' => '1 Pkt/3 Pcs', 'qty' => 1],
                    ['no' => 60, 'name' => 'Purple Dove (Ayyan)', 'pack' => '1 Box/1Pce', 'qty' => 1],
                    ['no' => 61, 'name' => 'Lemon Tree Fountain (4 Colour Varities)', 'pack' => '1Pce', 'qty' => 1],
                    ['no' => 62, 'name' => 'Barlie Purple / Jea Boom Ba Blue', 'pack' => '1Pce', 'qty' => 1],
                    ['no' => 63, 'name' => 'Mowgli 28 Chorsa', 'pack' => '1 Box/5 Pcs', 'qty' => 1],
                    ['no' => 64, 'name' => '100 W-power', 'pack' => '1 Box/3 Pcs', 'qty' => 1],
                    ['no' => 65, 'name' => '500G', 'pack' => '1 Box/ 1 Pce', 'qty' => 1],
                    ['no' => 66, 'name' => '1KG', 'pack' => '1 Box/ 1 Pce', 'qty' => 1],
                ],
            ],
        ];
    }

    /**
     * Display the Combo Offers page
     */
    public function index()
    {
        $combos = self::getCombos();
        return view('pages.combos', compact('combos'));
    }
}
